default: syntax
	@echo "Running syntax"
	@./syntax

syntax:
	@echo "Compiling syntax.cpp"
	@g++ -Wall -Wextra -Werror syntax.cpp -o syntax

clean:
	@echo "Deleting executables"
	@rm syntax
