default: pointers
	@echo "Running pointers"
	@./pointers

pointers: pointers.cpp
	@echo "Compiling pointers.cpp"
	@g++ -Wall -Wextra -Werror pointers.cpp -o pointers

clean:
	@echo "Removing executables"
	@rm pointers
